export type MerchantRole = 'OWNER' | 'ADMIN' | 'DEVELOPER' | 'FINANCE' | 'VIEWER';

const PERMISSIONS: Record<MerchantRole, Set<string>> = {
  OWNER: new Set([
    'PAYMENT:READ', 'PAYMENT:CREATE', 'PAYMENT:EXECUTE',
    'REFUND:READ', 'REFUND:CREATE', 'REFUND:UPDATE', 'REFUND:DELETE', 'REFUND:EXECUTE',
    'CHARGEBACK:READ', 'CHARGEBACK:CREATE', 'CHARGEBACK:UPDATE', 'CHARGEBACK:DELETE', 'CHARGEBACK:EXECUTE',
    'API_KEY:READ', 'API_KEY:CREATE', 'API_KEY:UPDATE', 'API_KEY:DELETE',
    'WEBHOOK:READ', 'WEBHOOK:CREATE', 'WEBHOOK:UPDATE', 'WEBHOOK:DELETE',
    'ROUTING_RULE:READ', 'ROUTING_RULE:CREATE', 'ROUTING_RULE:UPDATE', 'ROUTING_RULE:DELETE',
    'CONNECTOR:READ', 'CONNECTOR:CREATE', 'CONNECTOR:UPDATE', 'CONNECTOR:DELETE',
    'LOG:READ',
    'MEMBER:READ', 'MEMBER:CREATE', 'MEMBER:UPDATE', 'MEMBER:DELETE',
    'MERCHANT_SETTINGS:READ', 'MERCHANT_SETTINGS:UPDATE', 'MERCHANT_SETTINGS:DELETE',
  ]),
  ADMIN: new Set([
    'PAYMENT:READ', 'PAYMENT:CREATE', 'PAYMENT:EXECUTE',
    'REFUND:READ', 'REFUND:CREATE', 'REFUND:UPDATE', 'REFUND:DELETE', 'REFUND:EXECUTE',
    'API_KEY:READ', 'API_KEY:CREATE', 'API_KEY:UPDATE', 'API_KEY:DELETE',
    'WEBHOOK:READ', 'WEBHOOK:CREATE', 'WEBHOOK:UPDATE', 'WEBHOOK:DELETE',
    'ROUTING_RULE:READ', 'ROUTING_RULE:CREATE', 'ROUTING_RULE:UPDATE', 'ROUTING_RULE:DELETE',
    'CONNECTOR:READ', 'CONNECTOR:CREATE', 'CONNECTOR:UPDATE', 'CONNECTOR:DELETE',
    'LOG:READ',
    'MEMBER:READ', 'MEMBER:CREATE', 'MEMBER:UPDATE', 'MEMBER:DELETE',
    'MERCHANT_SETTINGS:READ', 'MERCHANT_SETTINGS:UPDATE',
  ]),
  DEVELOPER: new Set([
    'PAYMENT:READ',
    'API_KEY:READ', 'API_KEY:CREATE', 'API_KEY:UPDATE', 'API_KEY:DELETE',
    'WEBHOOK:READ', 'WEBHOOK:CREATE', 'WEBHOOK:UPDATE', 'WEBHOOK:DELETE',
    'ROUTING_RULE:READ', 'ROUTING_RULE:CREATE', 'ROUTING_RULE:UPDATE', 'ROUTING_RULE:DELETE',
    'CONNECTOR:READ',
    'LOG:READ',
    'MERCHANT_SETTINGS:READ',
  ]),
  FINANCE: new Set([
    'PAYMENT:READ', 'PAYMENT:CREATE', 'PAYMENT:EXECUTE',
    'REFUND:READ', 'REFUND:CREATE', 'REFUND:UPDATE', 'REFUND:DELETE', 'REFUND:EXECUTE',
    'CHARGEBACK:READ', 'CHARGEBACK:CREATE', 'CHARGEBACK:UPDATE', 'CHARGEBACK:DELETE', 'CHARGEBACK:EXECUTE',
    'LOG:READ',
    'MERCHANT_SETTINGS:READ',
  ]),
  VIEWER: new Set([
    'PAYMENT:READ',
    'LOG:READ',
    'MERCHANT_SETTINGS:READ',
  ]),
};

export function can(role: MerchantRole | null | undefined, resource: string, action: string): boolean {
  if (!role) return false;
  return PERMISSIONS[role]?.has(`${resource}:${action}`) ?? false;
}
