apiVersion: v1
kind: ConfigMap
metadata:
  name: masonxpay-config
data:
  REDIS_HOT_PATH_ENABLED: "true"
  REDIS_RATE_LIMIT_ENABLED: "true"
  REDIS_IDEMPOTENCY_CACHE_ENABLED: "true"
  REDIS_PROVIDER_HEALTH_CACHE_ENABLED: "true"
  REDIS_HEALTH_ENABLED: "true"
