apiVersion: v1
kind: Service
metadata:
  name: rail-simulator
spec:
  selector:
    app: rail-simulator
  ports:
    - name: http-admin
      port: 9090
      targetPort: 9090
    - name: iso8583-tcp
      port: 9091
      targetPort: 9091
